
#ifndef GAME_HARDWARE_DEFINITIONS_H_
#define GAME_HARDWARE_DEFINITIONS_H_

#define SCREEN_X_SIZE 160
#define SCREEN_Y_SIZE 144

#define BACKGROUND_X_SIZE 256
#define BACKGROUND_Y_SIZE 256

#define OAM_START_LOCATION 0xFE00
#define OAM_END_LOCATION 0xFE9F

#endif  // GAME_HARDWARE_DEFINITIONS_H_