
#ifndef GAME_PREFIXED_OPCODES_H_
#define GAME_PREFIXED_OPCODES_H_

#define OPCODE_PREFIX 0xCB

#define RES_7_aHL 0xBE

#define SET_7_aHL 0xFE

#define SET_1_aHL 0xCE

#endif  // GAME_PREFIXED_OPCODES_H_